### ISSUE TITLE
Dokuwiki gives blank white page

### ISSUE THREAD

**Issue by animeai** [gkrid/dokuwiki-plugin-ireadit#13]
Server environment:
- Ubuntu 16.04
- PHP 7.2
- MySQL 5.6
- Nginx as reverse proxy to Apache for php (Nginx serves static content only)

Webserver error logs: (IP, Server path and URL redacted for privacy)

`[Mon Aug 12 11:41:30.482823 2019] [:error] [pid 9146] [client [redacted ip]:40830] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php:117\nStack trace:\n#0 /home/[redacted server path]/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#1 /home/[redacted server path]/public_html/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /home/[redacted server path]/public_html/inc/parserutils.php(502): Doku_Event->advise_after()\n#3 /home/[redacted server path]/public_html/inc/parserutils.php(272): p_render_metadata('wiki:welcome', Array)\n#4 /home/[redacted server path]/public_html/inc/common.php(251): p_get_metadata('wiki:welcome')\n#5 /home/[redacted server path]/public_html/doku.php(91): pageinfo()\n#6 {main}\n  thrown in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php on line 117, referer: https://[redacted url].co.uk/doku.php?id=wiki:welcome&do=admin&page=extension&tab=search&q=
[Mon Aug 12 11:41:51.377396 2019] [:error] [pid 9151] [client [redacted ip]:40832] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php:117\nStack trace:\n#0 /home/[redacted server path]/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#1 /home/[redacted server path]/public_html/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /home/[redacted server path]/public_html/inc/parserutils.php(502): Doku_Event->advise_after()\n#3 /home/[redacted server path]/public_html/inc/parserutils.php(272): p_render_metadata('wiki:welcome', Array)\n#4 /home/[redacted server path]/public_html/inc/common.php(251): p_get_metadata('wiki:welcome')\n#5 /home/[redacted server path]/public_html/doku.php(91): pageinfo()\n#6 {main}\n  thrown in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php on line 117, referer: https://[redacted url].co.uk/doku.php?id=wiki:welcome&do=admin&page=extension&tab=search&q=
[Mon Aug 12 11:41:52.887429 2019] [:error] [pid 9144] [client [redacted ip]:40834] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php:117\nStack trace:\n#0 /home/[redacted server path]/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#1 /home/[redacted server path]/public_html/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /home/[redacted server path]/public_html/inc/parserutils.php(502): Doku_Event->advise_after()\n#3 /home/[redacted server path]/public_html/inc/parserutils.php(272): p_render_metadata('wiki:welcome', Array)\n#4 /home/[redacted server path]/public_html/inc/common.php(251): p_get_metadata('wiki:welcome')\n#5 /home/[redacted server path]/public_html/doku.php(91): pageinfo()\n#6 {main}\n  thrown in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php on line 117, referer: https://[redacted url].co.uk/doku.php?id=wiki:welcome&do=admin&page=extension&tab=search&q=
[Mon Aug 12 11:42:04.000284 2019] [:error] [pid 9147] [client [redacted ip]:40836] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php:117\nStack trace:\n#0 /home/[redacted server path]/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#1 /home/[redacted server path]/public_html/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /home/[redacted server path]/public_html/inc/parserutils.php(502): Doku_Event->advise_after()\n#3 /home/[redacted server path]/public_html/inc/parserutils.php(272): p_render_metadata('wiki:welcome', Array)\n#4 /home/[redacted server path]/public_html/inc/common.php(251): p_get_metadata('wiki:welcome')\n#5 /home/[redacted server path]/public_html/doku.php(91): pageinfo()\n#6 {main}\n  thrown in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php on line 117
[Mon Aug 12 11:42:11.175734 2019] [:error] [pid 9145] [client [redacted ip]:40838] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php:117\nStack trace:\n#0 /home/[redacted server path]/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#1 /home/[redacted server path]/public_html/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /home/[redacted server path]/public_html/inc/parserutils.php(502): Doku_Event->advise_after()\n#3 /home/[redacted server path]/public_html/inc/parserutils.php(272): p_render_metadata('wiki:welcome', Array)\n#4 /home/[redacted server path]/public_html/inc/common.php(251): p_get_metadata('wiki:welcome')\n#5 /home/[redacted server path]/public_html/doku.php(91): pageinfo()\n#6 {main}\n  thrown in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php on line 117
[Mon Aug 12 12:18:05.625491 2019] [:error] [pid 9145] [client [redacted ip]:41244] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php:117\nStack trace:\n#0 /home/[redacted server path]/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#1 /home/[redacted server path]/public_html/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /home/[redacted server path]/public_html/inc/parserutils.php(502): Doku_Event->advise_after()\n#3 /home/[redacted server path]/public_html/inc/parserutils.php(272): p_render_metadata('sidebar', Array)\n#4 /home/[redacted server path]/public_html/inc/common.php(251): p_get_metadata('sidebar')\n#5 /home/[redacted server path]/public_html/doku.php(91): pageinfo()\n#6 {main}\n  thrown in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php on line 117, referer: https://[redacted url].co.uk/sidebar?do=edit
[Mon Aug 12 12:18:11.277771 2019] [:error] [pid 9144] [client [redacted ip]:41246] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php:117\nStack trace:\n#0 /home/[redacted server path]/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#1 /home/[redacted server path]/public_html/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /home/[redacted server path]/public_html/inc/parserutils.php(502): Doku_Event->advise_after()\n#3 /home/[redacted server path]/public_html/inc/parserutils.php(272): p_render_metadata('sidebar', Array)\n#4 /home/[redacted server path]/public_html/inc/cache.php(290): p_get_metadata('sidebar', 'date valid')\n#5 /home/[redacted server path]/public_html/inc/cache.php(50): cache_renderer->_addDependencies()\n#6 /home/[redacted server path]/public_html/inc/parserutils.php(124): cache->use in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php on line 117
[Mon Aug 12 12:18:14.655364 2019] [:error] [pid 29160] [client [redacted ip]:41254] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php:117\nStack trace:\n#0 /home/[redacted server path]/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#1 /home/[redacted server path]/public_html/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /home/[redacted server path]/public_html/inc/parserutils.php(502): Doku_Event->advise_after()\n#3 /home/[redacted server path]/public_html/inc/parserutils.php(272): p_render_metadata('sidebar', Array)\n#4 /home/[redacted server path]/public_html/inc/cache.php(290): p_get_metadata('sidebar', 'date valid')\n#5 /home/[redacted server path]/public_html/inc/cache.php(50): cache_renderer->_addDependencies()\n#6 /home/[redacted server path]/public_html/inc/parserutils.php(124): cache->use in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php on line 117, referer: https://[redacted url].co.uk/
[Mon Aug 12 12:20:21.996564 2019] [:error] [pid 26190] [client [redacted ip]:41266] PHP Fatal error:  Uncaught Error: Call to a member function query() on boolean in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php:117\nStack trace:\n#0 /home/[redacted server path]/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#1 /home/[redacted server path]/public_html/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')\n#2 /home/[redacted server path]/public_html/inc/parserutils.php(502): Doku_Event->advise_after()\n#3 /home/[redacted server path]/public_html/inc/parserutils.php(272): p_render_metadata('sidebar', Array)\n#4 /home/[redacted server path]/public_html/inc/cache.php(290): p_get_metadata('sidebar', 'date valid')\n#5 /home/[redacted server path]/public_html/inc/cache.php(50): cache_renderer->_addDependencies()\n#6 /home/[redacted server path]/public_html/inc/parserutils.php(124): cache->use in /home/[redacted server path]/public_html/lib/plugins/ireadit/action/display.php on line 117, referer: https://[redacted url].co.uk/
2019/08/12 15:57:34 [crit] 9152#9152: *907 open() "/home/[redacted server path]/public_html/data/dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png" failed (13: Permission denied), client: 109.123.90.183, server: [redacted url].co.uk, request: "GET /data/dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png HTTP/1.1", host: "[redacted url].co.uk", referrer: "https://[redacted url].co.uk/home?do=admin"
[Mon Aug 12 15:57:34.884354 2019] [access_compat:error] [pid 9151] [client [redacted ip]:42502] AH01797: client denied by server configuration: /home/[redacted server path]/public_html/data/dont-panic-if-you-see-this-in-your-logs-it-means-your-directory-permissions-are-correct.png, referer: https://[redacted url].co.uk/home?do=admin
`

Error was only fixed by deleting the ireadit plugin directory.

**Comment by solewniczak** [comment]
You have to install sqlite plugin in order to use new ireadit.

**Comment by animeai** [comment]
Very strange.... Is this a new requirement? I've been using this plugin for about a year and a half now and this only started happening when I upgraded to the latest version...

**Comment by animeai** [comment]
Nope.... that didn't fix it. Same issue after installing the sqlite plugin.

`[Thu Aug 15 09:42:59.277959 2019] [:error] [pid 11595] [client redactedip:56670] PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /home/redactedpath/public_html/lib/plugins/ireadit/helper/db.php:44\nStack trace:\n#0 /home/redactedpath/public_html/lib/plugins/ireadit/helper/db.php(25): helper_plugin_ireadit_db->init()\n#1 /homeredactedpath/public_html/inc/plugincontroller.class.php(109): helper_plugin_ireadit_db->__construct()\n#2 /home/redactedpath.co.uk/public_html/inc/pluginutils.php(45): Doku_Plugin_Controller->load('helper', 'ireadit_db', false, false)\n#3 /homeredactedpath/public_html/lib/plugins/ireadit/action/display.php(108): plugin_load('helper', 'ireadit_db')\n#4 /homeredactedpath/public_html/inc/events.php(229): action_plugin_ireadit_display->updatre_ireadit_metadata(Object(Doku_Event), NULL)\n#5 /homeredactedpath/public_html/inc/events.php(79): Doku_Event_Handler->process_ in /homeredactedpath/public_html/lib/plugins/ireadit/helper/db.php on line 44`

**Comment by solewniczak** [comment]
SQLite is a new requirement that was added to integrate ireadit with [notification](https://www.dokuwiki.org/plugin:notification) plugin. This will allow notify users about pages that they need to read.  To use new ireadit you have to install `php-sqlite3` package.

If you prefer to stay with the previous version without notification support, you can download it from [here](https://github.com/gkrid/dokuwiki-plugin-ireadit/archive/d6e52e04a41e0a92f85216762ccb761147c09d65.zip). Remember to delete the newer version of plugin before installing the older one.

**Comment by eric-it6** [comment]
Hello everyone, I have the same problem.
I have installed ireadit and SQLite v2 with the extension manager. I always get a blank white page. Additionally I installed the package `php-sqlite3`, nothing changed.
<pre>
[Wed Jun 02 15:52:34.277393 2021] [php7:error] [pid 1031721] [client 172.20.1.45:38658] PHP Fatal error:  Uncaught Error:
Call to a member function getName() on null in /var/www/foo/htdocs/foo/lib/plugins/ireadit/helper
/db.php:44\nStack trace:\n#0 /var/www/foo/htdocs/foo/lib/plugins/ireadit/helper/db.php(25): 
helper_plugin_ireadit_db->init()\n#1 /var/www/foo/htdocs/foo/inc/Extension/PluginController.php(128): 
helper_plugin_ireadit_db->__construct()\n#2 /var/www/foo/htdocs/foo/inc/pluginutils.php(54): 
dokuwiki\\Extension\\PluginController->load()\n#3 /var/www/foo/htdocs/foo/lib/plugins/ireadit/action
/ireadit.php(113): plugin_load()\n#4 /var/www/foo/htdocs/foo/inc/Extension/EventHandler.php(81): 
action_plugin_ireadit_ireadit->updatre_ireadit_metadata()\n#5 /var/www/foo/htdocs/foo/inc/Extension
/Event.php(93): dokuwiki\\Extension\\EventHandler->process_event()\n#6 /var/www/foo/htdocs/foo
/inc/parserutils.php(521): dokuwiki\\Extension\\Event->advise_after()\n#7 /var/www/wiki.i in /var/www/foo
/htdocs/foo/lib/plugins/ireadit/helper/db.php on line 44, referer: https://foo/foo
/doku.php?id=start&do=admin&page=extension&tab=search&q=
</pre>

Do you have any news from this problem? 
Maybe another plugin is not compatible. I'll try to install the plugin manually.

Many greetings

**Comment by eric-it6** [comment]
Sorry, that was my mistake! I had not activated the plugin yet.
